apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifotosdb
  labels:
    app: ifotosdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifotosdb
  template:
    metadata:
      labels:
        app: ifotosdb
    spec:
      containers:
      - name: ifotosdb
        image: ifriedman7/ifotosdb:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 3306
        env:
        - name: IFOTOS_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: ifotos-secret
              key: ifotosdb-root-username
        - name: IFOTOS_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: ifotos-secret
              key: ifotosdb-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: ifotosdb-service
spec:
  selector:
    app: ifotosdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
