apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ifotos-s3provider
  labels:
    app: ifotos-s3provider
spec:
  template:
    metadata:
      labels:
        app: ifotos-s3provider
    spec:
      containers:
      - name: ifotos-s3provider
        image: efrecon/s3fs
#        image: meain/s3-mounter
        securityContext:
          privileged: true
        env:
        - name: AWS_S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ifotos-secret
              key: AWS_S3_ACCESS_KEY_ID
        - name: AWS_S3_SECRET_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: ifotos-secret
              key: AWS_S3_SECRET_ACCESS_KEY
        - name: AWS_S3_BUCKET
          valueFrom: 
            configMapKeyRef:
              name: ifotos-configmap
              key: AWS_S3_BUCKET
        volumeMounts:
        - name: devfuse
          mountPath: /dev/fuse
        - name: mntdatas3fs
          mountPath: /var/s3fs:shared
      volumes:
      - name: devfuse
        hostPath:
          path: /dev/fuse
      - name: mntdatas3fs
        hostPath:
          path: /home/s3data